name: scanBit_xkcd_1337
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bcftools=1.21
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.1.31
  - gsl=2.7
  - htslib=1.21
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.43
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.13.0
  - libdeflate=1.23
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.6
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libnsl=2.0.1
  - libopenblas=0.3.29
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libuuid=2.38.1
  - libxcrypt=4.4.36
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.5.0
  - perl=5.32.1
  - pip=25.0.1
  - python=3.12.9
  - readline=8.2
  - samtools=1.21
  - setuptools=78.1.0
  - tk=8.6.13
  - wheel=0.45.1
  - zstd=1.5.7
  - pip:
      - contourpy==1.3.1
      - cycler==0.12.1
      - fonttools==4.57.0
      - kiwisolver==1.4.8
      - matplotlib==3.10.1
      - numpy==2.2.4
      - packaging==24.2
      - pandas==2.2.3
      - pillow==11.1.0
      - pyparsing==3.2.3
      - pysam==0.23.0
      - python-dateutil==2.9.0.post0
      - pytz==2025.2
      - scipy==1.15.2
      - six==1.17.0
      - tzdata==2025.2
variables:
  scanBit_version: 0.6.0
