#!/bin/sh
#SBATCH --account=placeholder_account
#SBATCH --job-name=rrr_bam_split
#SBATCH --output=placeholder_slurm_out
#SBATCH --error=placeholder_slurm_out
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=2
#SBATCH --mem=80G
#SBATCH --partition=general,himem
#SBATCH --wait
placeholder_sbatch_other

set -e ### stops bash script if line ends with error

echo ${HOSTNAME}

cell_file=placeholder_cell_file
bam_file=placeholder_bam_file
bam_dir=placeholder_bam_dir

if [ ! -d ${sam_dir} ]
then
    mkdir -p ${sam_dir}
fi

echo ${bam_file}

ml purge
ml load Miniconda3/4.9.2
eval "$(conda shell.bash hook)"
conda activate rrrSNVs_xkcd_1337

python placeholder_py_file \
    --cells ${cell_file} \
    --out_dir ${bam_dir}/ \
    --bam ${bam_file}
