#!/bin/sh
#SBATCH --account=placeholder_account
#SBATCH --output=placeholder_slurm_out
#SBATCH --error=placeholder_slurm_out
#SBATCH --job-name rrr_merge
#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=4
#SBATCH --mem=10G
#SBATCH --partition=himem,general
#SBATCH --wait
#SBATCH --time=1-00:00:00

set -e ### stops bash script if line ends with error

echo ${HOSTNAME} ${SLURM_ARRAY_TASK_ID}

ml purge
ml load GCC/9.3.0 \
        GCCcore/9.3.0 \
        SAMtools/1.15 \
        BCFtools/1.11 \
        Miniconda3/4.9.2

eval "$(conda shell.bash hook)"
conda activate rrrSNVs_xkcd_1337

bcftools merge \
        --threads 4 \
        -O u \
        placeholder_bcf_dir/*.bcf \
    | bcftools view \
        -i 'GT[*]="alt"' \
        -O b \
        --output placeholder_bcf_out

bcftools index \
    --threads 4 \
    placeholder_bcf_out
